import type { CreateIntakeTemplateDto } from './dto/manage-intake-template.dto';

export const intakeTemplateDefaults: CreateIntakeTemplateDto[] = [
  {
    kind: 'guest',
    name: 'Winners Chapel First Timer Intake',
    slug: 'winners-first-timer',
    isActive: true,
    badge: 'First Time Worshipper Form',
    title: "Winners Chapel Int'l Atlanta",
    subtitle: 'Welcome home. Help us receive you well.',
    introTitle: 'We are honored you worshipped with us today',
    introBody:
      'Please complete this first timer form with the information needed for follow-up, prayer, and your next step. We welcome you and pray that the word you received becomes a lasting testimony in your life.',
    closingText: 'Jesus is Lord.',
    submitLabel: 'Submit First Timer Form',
    successTitle: 'Thank you for connecting',
    successMessage: 'Your first timer details have been received. Someone from the church will follow up with you soon.',
    logoPath: '/logo.png',
    theme: {
      accentColor: '#dc2626',
      darkColor: '#111827',
      softColor: '#fff7ed',
    },
    fields: [
      { key: 'visitDate', label: "Today's date", type: 'date', required: true, width: 'half' },
      { key: 'firstName', label: 'First name', type: 'text', required: true, placeholder: 'First Name', width: 'half' },
      { key: 'lastName', label: 'Last name', type: 'text', required: true, placeholder: 'Last Name', width: 'half' },
      { key: 'email', label: 'Email', type: 'email', required: true, helpText: 'This address can receive a confirmation email.', width: 'full' },
      { key: 'phone', label: 'Phone', type: 'tel', required: true, width: 'full' },
      { key: 'address', label: 'Street address', type: 'text', required: true, width: 'full' },
      { key: 'city', label: 'City', type: 'text', required: true, width: 'half' },
      { key: 'state', label: 'State', type: 'text', required: true, width: 'half' },
      { key: 'zipCode', label: 'Zip code', type: 'text', required: false, width: 'half' },
      { key: 'gender', label: 'Gender', type: 'radio', required: true, width: 'half', options: ['Male', 'Female'] },
      { key: 'cameWithFamily', label: 'Did you come with your family?', type: 'radio', required: true, width: 'half', options: ['Yes', 'No'] },
      {
        key: 'heardAboutChurch',
        label: 'How did you hear about us?',
        type: 'radio',
        required: true,
        width: 'full',
        options: ['Instagram', 'Evangelism (flyer)', 'A friend', 'Internet', 'Other'],
      },
      { key: 'invitedBy', label: 'Who invited you?', type: 'text', required: false, width: 'half' },
      { key: 'prayerRequest', label: 'Prayer request', type: 'textarea', required: false, width: 'full' },
    ],
  },
  {
    kind: 'member',
    name: 'Member Intake and Growth Record',
    slug: 'member-growth-record',
    isActive: true,
    badge: 'Member Intake Form',
    title: "Winners Chapel Int'l Atlanta",
    subtitle: 'Member growth, belonging, and formation in one record.',
    introTitle: 'Help us keep your member record accurate',
    introBody:
      'This form helps the church track membership, discipleship milestones, classes, and baptism journey with clarity.',
    closingText: 'Thank you for staying planted and accountable in the house.',
    submitLabel: 'Submit Member Form',
    successTitle: 'Member record received',
    successMessage: 'Your member intake details have been submitted successfully.',
    logoPath: '/logo.png',
    theme: {
      accentColor: '#0f766e',
      darkColor: '#111827',
      softColor: '#ecfeff',
    },
    fields: [
      {
        key: 'dateJoinedChurch',
        label: 'Date joined the church',
        type: 'date',
        required: true,
        width: 'half',
        helpText: 'Use the day the member was received into this church branch.',
      },
      {
        key: 'title',
        label: 'Member title',
        type: 'select',
        required: false,
        width: 'half',
        options: ['bro', 'sister', 'pastor', 'deacon', 'deaconess', 'apostle', 'other'],
        helpText: 'Use the member’s church title when it applies.',
      },
      { key: 'firstName', label: 'First name', type: 'text', required: true, width: 'half' },
      { key: 'lastName', label: 'Last name', type: 'text', required: true, width: 'half' },
      { key: 'email', label: 'Email', type: 'email', required: true, width: 'half' },
      { key: 'phone', label: 'Phone number', type: 'tel', required: true, width: 'half' },
      { key: 'familyDetails', label: 'Family details', type: 'textarea', required: false, width: 'full' },
      {
        key: 'membershipStatus',
        label: 'Membership status',
        type: 'select',
        required: true,
        width: 'half',
        options: ['active', 'new_member', 'worker', 'inactive'],
        helpText: 'Choose the member’s current standing in the branch.',
      },
      {
        key: 'serviceUnitInterest',
        label: 'Service unit',
        type: 'select',
        required: false,
        width: 'half',
        options: [],
        helpText: 'This list is filled automatically from active service units in the branch.',
      },
      {
        key: 'believerFoundationClassStatus',
        label: 'Have you attended Believers Foundation Class?',
        type: 'select',
        required: true,
        width: 'half',
        options: ['yes', 'no'],
        helpText: 'Choose yes if this member has attended Believers Foundation Class.',
      },
      {
        key: 'believerFoundationClassDate',
        label: 'Believers Foundation Class date or year',
        type: 'date',
        required: false,
        width: 'half',
        helpText: 'Use the class date when known. If only the year is known, enter a representative date in that year.',
      },
      {
        key: 'believerFoundationClassLocation',
        label: 'Believers Foundation Class location',
        type: 'text',
        required: false,
        width: 'half',
      },
      {
        key: 'bccStatus',
        label: 'Have you attended BCC?',
        type: 'select',
        required: true,
        width: 'half',
        options: ['yes', 'no'],
        helpText: 'BCC is treated as a Bible school course record.',
      },
      { key: 'bccDate', label: 'BCC date or year', type: 'date', required: false, width: 'half' },
      { key: 'bccLocation', label: 'BCC location', type: 'text', required: false, width: 'half' },
      {
        key: 'lccStatus',
        label: 'Have you attended LCC?',
        type: 'select',
        required: true,
        width: 'half',
        options: ['yes', 'no'],
        helpText: 'LCC is treated as a Bible school course record.',
      },
      { key: 'lccDate', label: 'LCC date or year', type: 'date', required: false, width: 'half' },
      { key: 'lccLocation', label: 'LCC location', type: 'text', required: false, width: 'half' },
      {
        key: 'lcdStatus',
        label: 'Have you attended LCD?',
        type: 'select',
        required: true,
        width: 'half',
        options: ['yes', 'no'],
        helpText: 'LCD is treated as a Bible school course record.',
      },
      { key: 'lcdDate', label: 'LCD date or year', type: 'date', required: false, width: 'half' },
      { key: 'lcdLocation', label: 'LCD location', type: 'text', required: false, width: 'half' },
      {
        key: 'holySpiritBaptismStatus',
        label: 'Holy Ghost baptism received?',
        type: 'select',
        required: true,
        width: 'half',
        options: ['yes', 'no'],
      },
      {
        key: 'waterBaptismStatus',
        label: 'Water baptism completed?',
        type: 'select',
        required: true,
        width: 'half',
        options: ['yes', 'no'],
      },
    ],
  },
  {
    kind: 'attendance',
    name: 'Service Attendance Summary',
    slug: 'service-attendance-summary',
    isActive: true,
    badge: 'Attendance Summary Form',
    title: "Winners Chapel Int'l Atlanta",
    subtitle: 'Capture service-level attendance and ministry outcomes.',
    introTitle: 'Record the full service attendance summary',
    introBody:
      'Use this form after each service to submit the total men, women, children, adults, first timers, new converts, and Holy Spirit baptism counts together with the service metadata.',
    closingText: 'Accurate service reporting makes pastoral planning stronger.',
    submitLabel: 'Submit Attendance Summary',
    successTitle: 'Attendance summary submitted',
    successMessage: 'This service attendance summary has been recorded successfully.',
    logoPath: '/logo.png',
    theme: {
      accentColor: '#ea580c',
      darkColor: '#111827',
      softColor: '#fff7ed',
    },
    fields: [
      { key: 'serviceDate', label: 'Day of service', type: 'date', required: true, width: 'half' },
      {
        key: 'serviceType',
        label: 'Service type',
        type: 'select',
        required: true,
        width: 'half',
        options: [],
        helpText: 'This list is filled automatically from active service types in the branch.',
      },
      { key: 'serviceName', label: 'Service name', type: 'text', required: true, width: 'full' },
      { key: 'menCount', label: 'Number of men', type: 'number', required: true, width: 'half' },
      { key: 'womenCount', label: 'Number of women', type: 'number', required: true, width: 'half' },
      { key: 'childrenCount', label: 'Number of children', type: 'number', required: true, width: 'half' },
      { key: 'adultsCount', label: 'Number of adults', type: 'number', required: true, width: 'half' },
      { key: 'firstTimersCount', label: 'First timers', type: 'number', required: true, width: 'half' },
      { key: 'newConvertsCount', label: 'New converts', type: 'number', required: true, width: 'half' },
      { key: 'holySpiritBaptismCount', label: 'Baptism of the Holy Spirit', type: 'number', required: true, width: 'half' },
    ],
  },
  {
    kind: 'weekly_report',
    name: 'Weekly Spiritual Indices Report',
    slug: 'weekly-spiritual-indices',
    isActive: true,
    badge: 'Weekly Attendance Report',
    title: 'Winners Chapel International Inc.',
    subtitle: 'MTNSA - Stations Weekly Report - Spiritual Indices',
    introTitle: 'Submit this branch weekly report',
    introBody:
      'Use this weekly report to send attendance, growth, spiritual indices, cells, WSF, WOFBI, and remarks to your district. Previous attendance and recent averages are prefilled when branch history is available, but can be adjusted before submission.',
    closingText: 'District totals are compiled automatically from branch submissions.',
    submitLabel: 'Submit Weekly Report',
    successTitle: 'Weekly report received',
    successMessage: 'This branch weekly spiritual indices report has been submitted for district review.',
    logoPath: '/logo.png',
    theme: {
      accentColor: '#e11d48',
      darkColor: '#111827',
      softColor: '#fff7ed',
    },
    fields: [
      { key: 'reportWeek', label: 'Report week ending', type: 'date', required: true, width: 'half' },
      {
        key: 'currentAttendance',
        label: 'Current attendance',
        type: 'number',
        required: true,
        width: 'half',
        helpText: 'Total branch attendance for this reporting week.',
      },
      {
        key: 'previousAttendance',
        label: 'Previous attendance',
        type: 'number',
        required: false,
        width: 'half',
        helpText: 'Auto-filled from the latest attendance summary for this branch when available.',
      },
      {
        key: 'averageLastYear',
        label: 'Avg of last year',
        type: 'number',
        required: false,
        width: 'half',
        helpText: 'Auto-filled when enough historical branch summaries exist.',
      },
      {
        key: 'averageLastPeriod',
        label: 'Avg of recent summaries',
        type: 'number',
        required: false,
        width: 'half',
        helpText: 'Auto-filled from recent branch attendance summaries.',
      },
      { key: 'firstTimersCount', label: 'FT - First timers', type: 'number', required: false, width: 'half' },
      { key: 'newConvertsCount', label: 'NC - New converts', type: 'number', required: false, width: 'half' },
      { key: 'believersFoundationClassCount', label: 'BFC - Believers Foundation Class', type: 'number', required: false, width: 'half' },
      { key: 'holySpiritBaptismCount', label: 'HGB - Holy Ghost Baptism', type: 'number', required: false, width: 'half' },
      { key: 'waterBaptismCount', label: 'WB - Water Baptism', type: 'number', required: false, width: 'half' },
      { key: 'covenantHourOfPrayerAttendance', label: 'CHOP - Covenant Hour of Prayer', type: 'number', required: false, width: 'half' },
      { key: 'winnersSatelliteFellowshipAverage', label: 'WSF (AVG) - Winners Satellite Fellowship', type: 'number', required: false, width: 'half' },
      { key: 'cellCount', label: '# of cells', type: 'number', required: false, width: 'half' },
      { key: 'newCellCount', label: '# of new cells', type: 'number', required: false, width: 'half' },
      { key: 'wofbiAttendance', label: 'WOFBI T/# of', type: 'number', required: false, width: 'half' },
      { key: 'remarks', label: 'Remarks', type: 'textarea', required: false, width: 'full' },
    ],
  },
];
